const SUCCESS = 200;
const ERROR = 500;
const VALIDATION = 422;
const NOT_FOUND = 404;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;

export { SUCCESS, ERROR, VALIDATION, NOT_FOUND, UNAUTHORIZED, FORBIDDEN };
